import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
  direction: 'ltr' | 'rtl';
}

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (langCode: string) => void;
  languages: Language[];
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const languages: Language[] = [
    { code: 'en', name: 'English', flag: '🇺🇸', direction: 'ltr' },
    { code: 'es', name: 'Español', flag: '🇪🇸', direction: 'ltr' },
    { code: 'fr', name: 'Français', flag: '🇫🇷', direction: 'ltr' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪', direction: 'ltr' },
    { code: 'pt', name: 'Português', flag: '🇵🇹', direction: 'ltr' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦', direction: 'rtl' },
    { code: 'zh', name: '中文', flag: '🇨🇳', direction: 'ltr' },
    { code: 'ja', name: '日本語', flag: '🇯🇵', direction: 'ltr' }
  ];

  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  // Load saved language from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('app-language');
    if (savedLanguage) {
      const lang = languages.find(l => l.code === savedLanguage);
      if (lang) {
        setCurrentLanguage(lang);
      }
    }
  }, []);

  // Save language to localStorage and update document
  const setLanguage = (langCode: string) => {
    const lang = languages.find(l => l.code === langCode);
    if (lang) {
      setCurrentLanguage(lang);
      localStorage.setItem('app-language', langCode);
      
      // Update document direction
      document.documentElement.dir = lang.direction;
      document.documentElement.lang = langCode;
      
      // Dispatch language change event
      window.dispatchEvent(new CustomEvent('language:changed', { detail: lang }));
    }
  };

  // Translation function (mock for now)
  const t = (key: string): string => {
    const translations: Record<string, Record<string, string>> = {
      en: {
        'search.placeholder': 'Search documents, vessels, activities...',
        'search.results': 'Search Results',
        'search.searching': 'Searching...',
        'search.noResults': 'No results found',
        'search.tryDifferent': 'Try different keywords',
        'search.recentSearches': 'Recent Searches',
        'search.quickSearch': 'Quick Search',
        'search.resultsFound': 'results found',
        'search.pressEnter': 'Press Enter to select first result',
        'logout.confirm': 'Are you sure you want to log out? All unsaved data will be lost.',
        'logout.success': 'Session closed successfully',
        'logout.error': 'Error logging out. Local cleanup will proceed.',
        'logout.close': 'Close',
        'profile': 'Profile',
        'settings': 'Settings',
        'notifications': 'Notifications',
        'help': 'Help & Support',
        'language': 'Language',
        'notifications.title': 'Notifications',
        'notifications.filter.all': 'All',
        'notifications.filter.unread': 'Unread',
        'notifications.filter.high': 'High Priority',
        'notifications.quickSearch': 'Quick Search',
        'notifications.view': 'View Details',
        'notifications.count': 'notifications',
        'notifications.markAllRead': 'Mark all as read',
        'notifications.noNotifications': 'No notifications',
        'notifications.pageTitle': 'Notifications',
        'notifications.pageDescription': 'Manage and view all your notifications',
        'notifications.export': 'Export',
        'notifications.search': 'Search',
        'notifications.searchPlaceholder': 'Search notifications...',
        'notifications.filter.label': 'Filter',
        'notifications.filter.medium': 'Medium Priority',
        'notifications.filter.low': 'Low Priority',
        'notifications.category': 'Category',
        'notifications.category.all': 'All Categories',
        'notifications.showRead': 'Show Read',
        'notifications.unread': 'Unread',
        'notifications.markAsRead': 'Mark as read',
        'notifications.delete': 'Delete',
        'notifications.viewDetails': 'View Details',
        'notifications.noNotificationsDescription': 'Try adjusting your filters or search terms',
        'notifications.clearAll': 'Clear all',
        'help.pageTitle': 'Help & Support',
        'help.pageDescription': 'Find answers, get help, and contact support',
        'help.contactSupport': 'Contact Support',
        'help.searchPlaceholder': 'Search help articles, FAQs, and more...',
        'help.tabs.help': 'Help Articles',
        'help.tabs.faq': 'FAQ',
        'help.tabs.support': 'Support',
        'help.categories.all': 'All Categories',
        'help.categories.gettingStarted': 'Getting Started',
        'help.categories.documents': 'Documents',
        'help.categories.vessels': 'Vessels',
        'help.categories.activities': 'Activities',
        'help.categories.troubleshooting': 'Troubleshooting',
        'help.searchResults': 'Search Results',
        'help.readMore': 'Read More',
        'help.popularArticles': 'Popular Articles',
        'help.recentArticles': 'Recent Articles',
        'help.faq.helpful': 'Was this helpful?',
        'help.support.contactInfo': 'Contact Information',
        'help.support.phoneHours': '24/7 Support',
        'help.support.emailResponse': 'Response within 2 hours',
        'help.support.yourTickets': 'Your Support Tickets',
        'help.support.createTicket': 'Create Support Ticket',
        'help.support.title': 'Title',
        'help.support.titlePlaceholder': 'Brief description of your issue',
        'help.support.description': 'Description',
        'help.support.descriptionPlaceholder': 'Detailed description of your issue or question',
        'help.support.category': 'Category',
        'help.support.priority': 'Priority',
        'help.support.email': 'Email',
        'help.support.submit': 'Submit Ticket',
        'help.support.quickContact': 'Quick Contact',
        'help.support.cancel': 'Cancel',
        'help.support.formError': 'Form Error',
        'help.support.fillAllFields': 'Please fill in all required fields',
        'help.support.ticketCreated': 'Support Ticket Created',
        'help.support.ticketCreatedMessage': 'Your support ticket has been created successfully',
        'help.support.categories.general': 'General',
        'help.support.categories.technical': 'Technical',
        'help.support.categories.billing': 'Billing',
        'help.support.categories.feature': 'Feature Request',
        'help.support.priorities.low': 'Low',
        'help.support.priorities.medium': 'Medium',
        'help.support.priorities.high': 'High',
        'help.support.priorities.urgent': 'Urgent',
        'profile.pageTitle': 'User Profile',
        'profile.pageDescription': 'Manage your account settings and preferences',
        'profile.editProfile': 'Edit Profile',
        'profile.saveChanges': 'Save Changes',
        'profile.cancel': 'Cancel',
        'profile.profilePicture': 'Profile Picture',
        'profile.personalInformation': 'Personal Information',
        'profile.fullName': 'Full Name',
        'profile.email': 'Email',
        'profile.phone': 'Phone',
        'profile.department': 'Department',
        'profile.position': 'Position',
        'profile.location': 'Location',
        'profile.timezone': 'Timezone',
        'profile.bio': 'Bio',
        'profile.lastUpdated': 'Last updated',
        'profile.memberSince': 'Member since',
        'profile.upload': 'Upload',
        'profile.uploading': 'Uploading...',
        'profile.avatarUpdated': 'Avatar Updated',
        'profile.avatarUpdatedMessage': 'Your profile picture has been updated successfully',
        'profile.uploadFailed': 'Upload Failed',
        'profile.uploadFailedMessage': 'Failed to upload avatar. Please try again.',
        'profile.profileUpdated': 'Profile Updated',
        'profile.profileUpdatedMessage': 'Your profile has been updated successfully',
        'profile.updateFailed': 'Update Failed',
        'profile.updateFailedMessage': 'Failed to update profile. Please try again.',
        'profile.security': 'Security',
        'profile.password': 'Password',
        'profile.changePassword': 'Change Password',
        'profile.currentPassword': 'Current Password',
        'profile.newPassword': 'New Password',
        'profile.confirmPassword': 'Confirm New Password',
        'profile.passwordMismatch': 'Password Mismatch',
        'profile.passwordMismatchMessage': 'New password and confirmation do not match',
        'profile.passwordChanged': 'Password Changed',
        'profile.passwordChangedMessage': 'Your password has been changed successfully',
        'profile.passwordChangeFailed': 'Password Change Failed',
        'profile.passwordChangeFailedMessage': 'Failed to change password. Please try again.',
        'profile.lastChanged': 'Last changed',
        'profile.twoFactorAuth': 'Two-Factor Authentication',
        'profile.twoFactorStatus': '2FA Status',
        'profile.enable2FA': 'Enable 2FA',
        'profile.disable2FA': 'Disable 2FA',
        'profile.enabled': 'Enabled',
        'profile.disabled': 'Disabled',
        'profile.twoFactorEnabled': '2FA Enabled',
        'profile.twoFactorEnabledMessage': 'Two-factor authentication has been enabled',
        'profile.twoFactorDisabled': '2FA Disabled',
        'profile.twoFactorDisabledMessage': 'Two-factor authentication has been disabled',
        'profile.securityInformation': 'Security Information',
        'profile.passwordExpiry': 'Password Expiry',
        'profile.loginAttempts': 'Login Attempts',
        'profile.failedAttempts': 'failed attempts',
        'profile.preferences': 'Preferences',
        'profile.appearanceLanguage': 'Appearance & Language',
        'profile.language': 'Language',
        'profile.theme': 'Theme',
        'profile.light': 'Light',
        'profile.dark': 'Dark',
        'profile.auto': 'Auto',
        'profile.notificationPreferences': 'Notification Preferences',
        'profile.emailNotifications': 'Email Notifications',
        'profile.pushNotifications': 'Push Notifications',
        'profile.smsNotifications': 'SMS Notifications',
        'profile.notificationFrequency': 'Notification Frequency',
        'profile.immediate': 'Immediate',
        'profile.hourly': 'Hourly',
        'profile.daily': 'Daily',
        'profile.privacySettings': 'Privacy Settings',
        'profile.profileVisibility': 'Profile Visibility',
        'profile.public': 'Public',
        'profile.teamOnly': 'Team Only',
        'profile.private': 'Private',
        'profile.showEmail': 'Show Email Address',
        'profile.showPhone': 'Show Phone Number',
        'profile.savePreferences': 'Save Preferences',
        'profile.saving': 'Saving...',
        'profile.preferencesUpdated': 'Preferences Updated',
        'profile.preferencesUpdatedMessage': 'Your preferences have been updated successfully',
        'profile.preferencesUpdateFailed': 'Update Failed',
        'profile.preferencesUpdateFailedMessage': 'Failed to update preferences. Please try again.',
        'profile.activity': 'Activity',
        'profile.recentActivity': 'Recent Activity',
        'profile.exportActivityLog': 'Export Activity Log'
      },
      es: {
        'search.placeholder': 'Buscar documentos, buques, actividades...',
        'search.results': 'Resultados de Búsqueda',
        'search.searching': 'Buscando...',
        'search.noResults': 'No se encontraron resultados',
        'search.tryDifferent': 'Intenta con palabras diferentes',
        'search.recentSearches': 'Búsquedas Recientes',
        'search.quickSearch': 'Búsqueda Rápida',
        'search.resultsFound': 'resultados encontrados',
        'search.pressEnter': 'Presiona Enter para seleccionar el primer resultado',
        'logout.confirm': '¿Estás seguro de que quieres cerrar sesión? Se perderán todos los datos no guardados.',
        'logout.success': 'Sesión cerrada exitosamente',
        'logout.error': 'Error al cerrar sesión. Se procederá con la limpieza local.',
        'logout.close': 'Cerrar',
        'profile': 'Perfil',
        'settings': 'Configuración',
        'notifications': 'Notificaciones',
        'help': 'Ayuda y Soporte',
        'language': 'Idioma',
        'notifications.title': 'Notificaciones',
        'notifications.filter.all': 'Todas',
        'notifications.filter.unread': 'No leídas',
        'notifications.filter.high': 'Alta Prioridad',
        'notifications.quickSearch': 'Búsqueda Rápida',
        'notifications.view': 'Ver Detalles',
        'notifications.count': 'notificaciones',
        'notifications.markAllRead': 'Marcar todas como leídas',
        'notifications.noNotifications': 'No hay notificaciones',
        'notifications.pageTitle': 'Notificaciones',
        'notifications.pageDescription': 'Gestiona y visualiza todas tus notificaciones',
        'notifications.export': 'Exportar',
        'notifications.search': 'Buscar',
        'notifications.searchPlaceholder': 'Buscar notificaciones...',
        'notifications.filter.label': 'Filtro',
        'notifications.filter.medium': 'Prioridad Media',
        'notifications.filter.low': 'Prioridad Baja',
        'notifications.category': 'Categoría',
        'notifications.category.all': 'Todas las Categorías',
        'notifications.showRead': 'Mostrar Leídas',
        'notifications.unread': 'No Leída',
        'notifications.markAsRead': 'Marcar como leída',
        'notifications.delete': 'Eliminar',
        'notifications.viewDetails': 'Ver Detalles',
        'notifications.noNotificationsDescription': 'Intenta ajustar tus filtros o términos de búsqueda',
        'notifications.clearAll': 'Limpiar todo',
        'help.pageTitle': 'Ayuda y Soporte',
        'help.pageDescription': 'Encuentra respuestas, obtén ayuda y contacta soporte',
        'help.contactSupport': 'Contactar Soporte',
        'help.searchPlaceholder': 'Buscar artículos de ayuda, FAQs y más...',
        'help.tabs.help': 'Artículos de Ayuda',
        'help.tabs.faq': 'FAQ',
        'help.tabs.support': 'Soporte',
        'help.categories.all': 'Todas las Categorías',
        'help.categories.gettingStarted': 'Primeros Pasos',
        'help.categories.documents': 'Documentos',
        'help.categories.vessels': 'Buques',
        'help.categories.activities': 'Actividades',
        'help.categories.troubleshooting': 'Solución de Problemas',
        'help.searchResults': 'Resultados de Búsqueda',
        'help.readMore': 'Leer Más',
        'help.popularArticles': 'Artículos Populares',
        'help.recentArticles': 'Artículos Recientes',
        'help.faq.helpful': '¿Te fue útil?',
        'help.support.contactInfo': 'Información de Contacto',
        'help.support.phoneHours': 'Soporte 24/7',
        'help.support.emailResponse': 'Respuesta en 2 horas',
        'help.support.yourTickets': 'Tus Tickets de Soporte',
        'help.support.createTicket': 'Crear Ticket de Soporte',
        'help.support.title': 'Título',
        'help.support.titlePlaceholder': 'Descripción breve de tu problema',
        'help.support.description': 'Descripción',
        'help.support.descriptionPlaceholder': 'Descripción detallada de tu problema o pregunta',
        'help.support.category': 'Categoría',
        'help.support.priority': 'Prioridad',
        'help.support.email': 'Email',
        'help.support.submit': 'Enviar Ticket',
        'help.support.quickContact': 'Contacto Rápido',
        'help.support.cancel': 'Cancelar',
        'help.support.formError': 'Error en el Formulario',
        'help.support.fillAllFields': 'Por favor completa todos los campos requeridos',
        'help.support.ticketCreated': 'Ticket de Soporte Creado',
        'help.support.ticketCreatedMessage': 'Tu ticket de soporte ha sido creado exitosamente',
        'help.support.categories.general': 'General',
        'help.support.categories.technical': 'Técnico',
        'help.support.categories.billing': 'Facturación',
        'help.support.categories.feature': 'Solicitud de Función',
        'help.support.priorities.low': 'Baja',
        'help.support.priorities.medium': 'Media',
        'help.support.priorities.high': 'Alta',
        'help.support.priorities.urgent': 'Urgente',
        'profile.pageTitle': 'Profil Utilisateur',
        'profile.pageDescription': 'Gérez les paramètres et préférences de votre compte',
        'profile.editProfile': 'Modifier le Profil',
        'profile.saveChanges': 'Enregistrer les Modifications',
        'profile.cancel': 'Annuler',
        'profile.profilePicture': 'Photo de Profil',
        'profile.personalInformation': 'Informations Personnelles',
        'profile.fullName': 'Nom Complet',
        'profile.email': 'Adresse Email',
        'profile.phone': 'Téléphone',
        'profile.department': 'Département',
        'profile.position': 'Poste',
        'profile.location': 'Localisation',
        'profile.timezone': 'Fuseau Horaire',
        'profile.bio': 'Biographie',
        'profile.lastUpdated': 'Dernière mise à jour',
        'profile.memberSince': 'Membre depuis',
        'profile.upload': 'Télécharger',
        'profile.uploading': 'Téléchargement...',
        'profile.avatarUpdated': 'Avatar Mis à Jour',
        'profile.avatarUpdatedMessage': 'Votre photo de profil a été mise à jour avec succès',
        'profile.uploadFailed': 'Échec du Téléchargement',
        'profile.uploadFailedMessage': 'Échec du téléchargement de l\'avatar. Veuillez réessayer.',
        'profile.profileUpdated': 'Profil Mis à Jour',
        'profile.profileUpdatedMessage': 'Votre profil a été mis à jour avec succès',
        'profile.updateFailed': 'Échec de la Mise à Jour',
        'profile.updateFailedMessage': 'Échec de la mise à jour du profil. Veuillez réessayer.',
        'profile.security': 'Sécurité',
        'profile.password': 'Mot de Passe',
        'profile.changePassword': 'Changer le Mot de Passe',
        'profile.currentPassword': 'Mot de Passe Actuel',
        'profile.newPassword': 'Nouveau Mot de Passe',
        'profile.confirmPassword': 'Confirmer le Nouveau Mot de Passe',
        'profile.passwordMismatch': 'Mots de Passe Ne Correspondent Pas',
        'profile.passwordMismatchMessage': 'Le nouveau mot de passe et la confirmation ne correspondent pas',
        'profile.passwordChanged': 'Mot de Passe Changé',
        'profile.passwordChangedMessage': 'Votre mot de passe a été changé avec succès',
        'profile.passwordChangeFailed': 'Échec du Changement de Mot de Passe',
        'profile.passwordChangeFailedMessage': 'Échec du changement de mot de passe. Veuillez réessayer.',
        'profile.lastChanged': 'Dernier changement',
        'profile.twoFactorAuth': 'Authentification à Deux Facteurs',
        'profile.twoFactorStatus': 'Statut 2FA',
        'profile.enable2FA': 'Activer 2FA',
        'profile.disable2FA': 'Désactiver 2FA',
        'profile.enabled': 'Activé',
        'profile.disabled': 'Désactivé',
        'profile.twoFactorEnabled': '2FA Activé',
        'profile.twoFactorEnabledMessage': 'L\'authentification à deux facteurs a été activée',
        'profile.twoFactorDisabled': '2FA Désactivé',
        'profile.twoFactorDisabledMessage': 'L\'authentification à deux facteurs a été désactivée',
        'profile.securityInformation': 'Informations de Sécurité',
        'profile.passwordExpiry': 'Expiration du Mot de Passe',
        'profile.loginAttempts': 'Tentatives de Connexion',
        'profile.failedAttempts': 'tentatives échouées',
        'profile.preferences': 'Préférences',
        'profile.appearanceLanguage': 'Apparence et Langue',
        'profile.language': 'Langue',
        'profile.theme': 'Thème',
        'profile.light': 'Clair',
        'profile.dark': 'Sombre',
        'profile.auto': 'Automatique',
        'profile.notificationPreferences': 'Préférences de Notifications',
        'profile.emailNotifications': 'Notifications par Email',
        'profile.pushNotifications': 'Notifications Push',
        'profile.smsNotifications': 'Notifications SMS',
        'profile.notificationFrequency': 'Fréquence des Notifications',
        'profile.immediate': 'Immédiat',
        'profile.hourly': 'Toutes les Heures',
        'profile.daily': 'Quotidien',
        'profile.privacySettings': 'Paramètres de Confidentialité',
        'profile.profileVisibility': 'Visibilité du Profil',
        'profile.public': 'Public',
        'profile.teamOnly': 'Équipe Seulement',
        'profile.private': 'Privé',
        'profile.showEmail': 'Afficher l\'Adresse Email',
        'profile.showPhone': 'Afficher le Numéro de Téléphone',
        'profile.savePreferences': 'Enregistrer les Préférences',
        'profile.saving': 'Enregistrement...',
        'profile.preferencesUpdated': 'Préférences Mises à Jour',
        'profile.preferencesUpdatedMessage': 'Vos préférences ont été mises à jour avec succès',
        'profile.preferencesUpdateFailed': 'Échec de la Mise à Jour',
        'profile.preferencesUpdateFailedMessage': 'Échec de la mise à jour des préférences. Veuillez réessayer.',
        'profile.activity': 'Activité',
        'profile.recentActivity': 'Activité Récente',
        'profile.exportActivityLog': 'Exporter le Journal d\'Activité'
      },
      fr: {
        'search.placeholder': 'Rechercher des documents, navires, activités...',
        'search.results': 'Résultats de Recherche',
        'search.searching': 'Recherche en cours...',
        'search.noResults': 'Aucun résultat trouvé',
        'search.tryDifferent': 'Essayez des mots-clés différents',
        'search.recentSearches': 'Recherches Récentes',
        'search.quickSearch': 'Recherche Rapide',
        'search.resultsFound': 'résultats trouvés',
        'search.pressEnter': 'Appuyez sur Entrée pour sélectionner le premier résultat',
        'logout.confirm': 'Êtes-vous sûr de vouloir vous déconnecter ? Toutes les données non sauvegardées seront perdues.',
        'logout.success': 'Session fermée avec succès',
        'logout.error': 'Erreur lors de la déconnexion. Le nettoyage local se poursuivra.',
        'logout.close': 'Fermer',
        'profile': 'Profil',
        'settings': 'Paramètres',
        'notifications': 'Notifications',
        'help': 'Aide et Support',
        'language': 'Langue',
        'notifications.title': 'Notifications',
        'notifications.filter.all': 'Toutes',
        'notifications.filter.unread': 'Non lues',
        'notifications.filter.high': 'Haute Priorité',
        'notifications.quickSearch': 'Recherche Rapide',
        'notifications.view': 'Voir Détails',
        'notifications.count': 'notifications',
        'notifications.markAllRead': 'Marquer toutes comme lues',
        'notifications.noNotifications': 'Aucune notification',
        'notifications.pageTitle': 'Notifications',
        'notifications.pageDescription': 'Gérez et visualisez toutes vos notifications',
        'notifications.export': 'Exporter',
        'notifications.search': 'Rechercher',
        'notifications.searchPlaceholder': 'Rechercher des notifications...',
        'notifications.filter.label': 'Filtre',
        'notifications.filter.medium': 'Priorité Moyenne',
        'notifications.filter.low': 'Priorité Basse',
        'notifications.category': 'Catégorie',
        'notifications.category.all': 'Toutes les Catégories',
        'notifications.showRead': 'Afficher Lues',
        'notifications.unread': 'Non Lue',
        'notifications.markAsRead': 'Marquer comme lue',
        'notifications.delete': 'Supprimer',
        'notifications.viewDetails': 'Voir Détails',
        'notifications.noNotificationsDescription': 'Essayez d\'ajuster vos filtres ou termes de recherche',
        'notifications.clearAll': 'Tout effacer',
        'help.pageTitle': 'Aide et Support',
        'help.pageDescription': 'Trouvez des réponses, obtenez de l\'aide et contactez le support',
        'help.contactSupport': 'Contacter le Support',
        'help.searchPlaceholder': 'Rechercher des articles d\'aide, FAQ et plus...',
        'help.tabs.help': 'Articles d\'Aide',
        'help.tabs.faq': 'FAQ',
        'help.tabs.support': 'Support',
        'help.categories.all': 'Toutes les Catégories',
        'help.categories.gettingStarted': 'Premiers Pas',
        'help.categories.documents': 'Documents',
        'help.categories.vessels': 'Navires',
        'help.categories.activities': 'Activités',
        'help.categories.troubleshooting': 'Résolution de Problèmes',
        'help.searchResults': 'Résultats de Recherche',
        'help.readMore': 'Lire Plus',
        'help.popularArticles': 'Articles Populaires',
        'help.recentArticles': 'Articles Récents',
        'help.faq.helpful': 'Cela vous a-t-il aidé ?',
        'help.support.contactInfo': 'Informations de Contact',
        'help.support.phoneHours': 'Support 24/7',
        'help.support.emailResponse': 'Réponse en 2 heures',
        'help.support.yourTickets': 'Vos Tickets de Support',
        'help.support.createTicket': 'Créer un Ticket de Support',
        'help.support.title': 'Titre',
        'help.support.titlePlaceholder': 'Description brève de votre problème',
        'help.support.description': 'Description',
        'help.support.descriptionPlaceholder': 'Description détaillée de votre problème ou question',
        'help.support.category': 'Catégorie',
        'help.support.priority': 'Priorité',
        'help.support.email': 'Email',
        'help.support.submit': 'Soumettre le Ticket',
        'help.support.quickContact': 'Contact Rapide',
        'help.support.cancel': 'Annuler',
        'help.support.formError': 'Erreur de Formulaire',
        'help.support.fillAllFields': 'Veuillez remplir tous les champs requis',
        'help.support.ticketCreated': 'Ticket de Support Créé',
        'help.support.ticketCreatedMessage': 'Votre ticket de support a été créé avec succès',
        'help.support.categories.general': 'Général',
        'help.support.categories.technical': 'Technique',
        'help.support.categories.billing': 'Facturation',
        'help.support.categories.feature': 'Demande de Fonctionnalité',
        'help.support.priorities.low': 'Basse',
        'help.support.priorities.medium': 'Moyenne',
        'help.support.priorities.high': 'Haute',
        'help.support.priorities.urgent': 'Urgente'
      }
    };

    return translations[currentLanguage.code]?.[key] || key;
  };

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    languages,
    t,
    isRTL: currentLanguage.direction === 'rtl'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
