/**
 * COASTAL COUNTRIES - For STS Operations Location Validation
 * Phase 1: Dashboard Discoverability
 * 
 * Used in StsOperationWizard to restrict location selection to coastal countries only.
 * Data from UN UNCLOS (United Nations Convention on the Law of the Sea)
 */

export const COASTAL_COUNTRIES = [
  // Africa
  { name: 'Algeria', code: 'DZ', region: 'Africa' },
  { name: 'Angola', code: 'AO', region: 'Africa' },
  { name: 'Benin', code: 'BJ', region: 'Africa' },
  { name: 'Cameroon', code: 'CM', region: 'Africa' },
  { name: 'Cape Verde', code: 'CV', region: 'Africa' },
  { name: 'Côte d\'Ivoire', code: 'CI', region: 'Africa' },
  { name: 'Egypt', code: 'EG', region: 'Africa' },
  { name: 'Equatorial Guinea', code: 'GQ', region: 'Africa' },
  { name: 'Eritrea', code: 'ER', region: 'Africa' },
  { name: 'Gabon', code: 'GA', region: 'Africa' },
  { name: 'Gambia', code: 'GM', region: 'Africa' },
  { name: 'Ghana', code: 'GH', region: 'Africa' },
  { name: 'Guinea', code: 'GN', region: 'Africa' },
  { name: 'Guinea-Bissau', code: 'GW', region: 'Africa' },
  { name: 'Kenya', code: 'KE', region: 'Africa' },
  { name: 'Lesotho', code: 'LS', region: 'Africa' },
  { name: 'Liberia', code: 'LR', region: 'Africa' },
  { name: 'Libya', code: 'LY', region: 'Africa' },
  { name: 'Madagascar', code: 'MG', region: 'Africa' },
  { name: 'Mauritania', code: 'MR', region: 'Africa' },
  { name: 'Mauritius', code: 'MU', region: 'Africa' },
  { name: 'Morocco', code: 'MA', region: 'Africa' },
  { name: 'Mozambique', code: 'MZ', region: 'Africa' },
  { name: 'Namibia', code: 'NA', region: 'Africa' },
  { name: 'Nigeria', code: 'NG', region: 'Africa' },
  { name: 'Saint Helena', code: 'SH', region: 'Africa' },
  { name: 'Sao Tome and Principe', code: 'ST', region: 'Africa' },
  { name: 'Senegal', code: 'SN', region: 'Africa' },
  { name: 'Seychelles', code: 'SC', region: 'Africa' },
  { name: 'Sierra Leone', code: 'SL', region: 'Africa' },
  { name: 'Somalia', code: 'SO', region: 'Africa' },
  { name: 'South Africa', code: 'ZA', region: 'Africa' },
  { name: 'Sudan', code: 'SD', region: 'Africa' },
  { name: 'Tanzania', code: 'TZ', region: 'Africa' },
  { name: 'Togo', code: 'TG', region: 'Africa' },
  { name: 'Tunisia', code: 'TN', region: 'Africa' },

  // Americas
  { name: 'Antigua and Barbuda', code: 'AG', region: 'Americas' },
  { name: 'Bahamas', code: 'BS', region: 'Americas' },
  { name: 'Barbados', code: 'BB', region: 'Americas' },
  { name: 'Belize', code: 'BZ', region: 'Americas' },
  { name: 'Canada', code: 'CA', region: 'Americas' },
  { name: 'Costa Rica', code: 'CR', region: 'Americas' },
  { name: 'Cuba', code: 'CU', region: 'Americas' },
  { name: 'Dominica', code: 'DM', region: 'Americas' },
  { name: 'Dominican Republic', code: 'DO', region: 'Americas' },
  { name: 'Ecuador', code: 'EC', region: 'Americas' },
  { name: 'El Salvador', code: 'SV', region: 'Americas' },
  { name: 'Grenada', code: 'GD', region: 'Americas' },
  { name: 'Guatemala', code: 'GT', region: 'Americas' },
  { name: 'Guyana', code: 'GY', region: 'Americas' },
  { name: 'Haiti', code: 'HT', region: 'Americas' },
  { name: 'Honduras', code: 'HN', region: 'Americas' },
  { name: 'Jamaica', code: 'JM', region: 'Americas' },
  { name: 'Mexico', code: 'MX', region: 'Americas' },
  { name: 'Nicaragua', code: 'NI', region: 'Americas' },
  { name: 'Panama', code: 'PA', region: 'Americas' },
  { name: 'Peru', code: 'PE', region: 'Americas' },
  { name: 'Saint Kitts and Nevis', code: 'KN', region: 'Americas' },
  { name: 'Saint Lucia', code: 'LC', region: 'Americas' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', region: 'Americas' },
  { name: 'Suriname', code: 'SR', region: 'Americas' },
  { name: 'Trinidad and Tobago', code: 'TT', region: 'Americas' },
  { name: 'United States', code: 'US', region: 'Americas' },
  { name: 'Uruguay', code: 'UY', region: 'Americas' },
  { name: 'Venezuela', code: 'VE', region: 'Americas' },

  // Asia-Pacific
  { name: 'Australia', code: 'AU', region: 'Asia-Pacific' },
  { name: 'Bahrain', code: 'BH', region: 'Asia-Pacific' },
  { name: 'Bangladesh', code: 'BD', region: 'Asia-Pacific' },
  { name: 'Brunei', code: 'BN', region: 'Asia-Pacific' },
  { name: 'Cambodia', code: 'KH', region: 'Asia-Pacific' },
  { name: 'China', code: 'CN', region: 'Asia-Pacific' },
  { name: 'Fiji', code: 'FJ', region: 'Asia-Pacific' },
  { name: 'Hong Kong', code: 'HK', region: 'Asia-Pacific' },
  { name: 'India', code: 'IN', region: 'Asia-Pacific' },
  { name: 'Indonesia', code: 'ID', region: 'Asia-Pacific' },
  { name: 'Iran', code: 'IR', region: 'Asia-Pacific' },
  { name: 'Iraq', code: 'IQ', region: 'Asia-Pacific' },
  { name: 'Israel', code: 'IL', region: 'Asia-Pacific' },
  { name: 'Japan', code: 'JP', region: 'Asia-Pacific' },
  { name: 'Jordan', code: 'JO', region: 'Asia-Pacific' },
  { name: 'Kiribati', code: 'KI', region: 'Asia-Pacific' },
  { name: 'Kuwait', code: 'KW', region: 'Asia-Pacific' },
  { name: 'Laos', code: 'LA', region: 'Asia-Pacific' },
  { name: 'Lebanon', code: 'LB', region: 'Asia-Pacific' },
  { name: 'Malaysia', code: 'MY', region: 'Asia-Pacific' },
  { name: 'Maldives', code: 'MV', region: 'Asia-Pacific' },
  { name: 'Marshall Islands', code: 'MH', region: 'Asia-Pacific' },
  { name: 'Mauritius', code: 'MU', region: 'Asia-Pacific' },
  { name: 'Micronesia', code: 'FM', region: 'Asia-Pacific' },
  { name: 'Mongolia', code: 'MN', region: 'Asia-Pacific' },
  { name: 'Myanmar', code: 'MM', region: 'Asia-Pacific' },
  { name: 'Nauru', code: 'NR', region: 'Asia-Pacific' },
  { name: 'New Zealand', code: 'NZ', region: 'Asia-Pacific' },
  { name: 'North Korea', code: 'KP', region: 'Asia-Pacific' },
  { name: 'Oman', code: 'OM', region: 'Asia-Pacific' },
  { name: 'Palau', code: 'PW', region: 'Asia-Pacific' },
  { name: 'Pakistan', code: 'PK', region: 'Asia-Pacific' },
  { name: 'Papua New Guinea', code: 'PG', region: 'Asia-Pacific' },
  { name: 'Philippines', code: 'PH', region: 'Asia-Pacific' },
  { name: 'Qatar', code: 'QA', region: 'Asia-Pacific' },
  { name: 'Samoa', code: 'WS', region: 'Asia-Pacific' },
  { name: 'Saudi Arabia', code: 'SA', region: 'Asia-Pacific' },
  { name: 'Singapore', code: 'SG', region: 'Asia-Pacific' },
  { name: 'Solomon Islands', code: 'SB', region: 'Asia-Pacific' },
  { name: 'South Korea', code: 'KR', region: 'Asia-Pacific' },
  { name: 'Sri Lanka', code: 'LK', region: 'Asia-Pacific' },
  { name: 'Syria', code: 'SY', region: 'Asia-Pacific' },
  { name: 'Taiwan', code: 'TW', region: 'Asia-Pacific' },
  { name: 'Thailand', code: 'TH', region: 'Asia-Pacific' },
  { name: 'Timor-Leste', code: 'TL', region: 'Asia-Pacific' },
  { name: 'Tonga', code: 'TO', region: 'Asia-Pacific' },
  { name: 'Turkey', code: 'TR', region: 'Asia-Pacific' },
  { name: 'Tuvalu', code: 'TV', region: 'Asia-Pacific' },
  { name: 'United Arab Emirates', code: 'AE', region: 'Asia-Pacific' },
  { name: 'Vanuatu', code: 'VU', region: 'Asia-Pacific' },
  { name: 'Vietnam', code: 'VN', region: 'Asia-Pacific' },
  { name: 'Yemen', code: 'YE', region: 'Asia-Pacific' },

  // Europe
  { name: 'Albania', code: 'AL', region: 'Europe' },
  { name: 'Belgium', code: 'BE', region: 'Europe' },
  { name: 'Bulgaria', code: 'BG', region: 'Europe' },
  { name: 'Croatia', code: 'HR', region: 'Europe' },
  { name: 'Cyprus', code: 'CY', region: 'Europe' },
  { name: 'Denmark', code: 'DK', region: 'Europe' },
  { name: 'Estonia', code: 'EE', region: 'Europe' },
  { name: 'Finland', code: 'FI', region: 'Europe' },
  { name: 'France', code: 'FR', region: 'Europe' },
  { name: 'Germany', code: 'DE', region: 'Europe' },
  { name: 'Greece', code: 'GR', region: 'Europe' },
  { name: 'Greenland', code: 'GL', region: 'Europe' },
  { name: 'Guernsey', code: 'GG', region: 'Europe' },
  { name: 'Iceland', code: 'IS', region: 'Europe' },
  { name: 'Ireland', code: 'IE', region: 'Europe' },
  { name: 'Isle of Man', code: 'IM', region: 'Europe' },
  { name: 'Italy', code: 'IT', region: 'Europe' },
  { name: 'Jersey', code: 'JE', region: 'Europe' },
  { name: 'Latvia', code: 'LV', region: 'Europe' },
  { name: 'Lithuania', code: 'LT', region: 'Europe' },
  { name: 'Malta', code: 'MT', region: 'Europe' },
  { name: 'Netherlands', code: 'NL', region: 'Europe' },
  { name: 'Norway', code: 'NO', region: 'Europe' },
  { name: 'Poland', code: 'PL', region: 'Europe' },
  { name: 'Portugal', code: 'PT', region: 'Europe' },
  { name: 'Romania', code: 'RO', region: 'Europe' },
  { name: 'Russia', code: 'RU', region: 'Europe' },
  { name: 'San Marino', code: 'SM', region: 'Europe' },
  { name: 'Serbia', code: 'RS', region: 'Europe' },
  { name: 'Slovenia', code: 'SI', region: 'Europe' },
  { name: 'Spain', code: 'ES', region: 'Europe' },
  { name: 'Sweden', code: 'SE', region: 'Europe' },
  { name: 'Switzerland', code: 'CH', region: 'Europe' },
  { name: 'Ukraine', code: 'UA', region: 'Europe' },
  { name: 'United Kingdom', code: 'GB', region: 'Europe' },
];

// Helper function to get coastal countries by region
export const getCoastalCountriesByRegion = (region: string) => {
  return COASTAL_COUNTRIES.filter(country => country.region === region);
};

// Helper function to check if a location is a valid coastal country
export const isValidCoastalCountry = (location: string): boolean => {
  return COASTAL_COUNTRIES.some(
    country => 
      country.name.toLowerCase() === location.toLowerCase() ||
      country.code.toLowerCase() === location.toLowerCase()
  );
};

// Get all unique regions
export const COASTAL_REGIONS = [...new Set(COASTAL_COUNTRIES.map(c => c.region))].sort();