apiVersion: v1
kind: Namespace
metadata:
  name: sts-production
  labels:
    name: sts-production
    environment: production
    app: sts-clearance-hub
  annotations:
    description: "Production namespace for STS Clearance Hub"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sts-production-quota
  namespace: sts-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sts-production-limits
  namespace: sts-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim