# This file should not be here - actionlint config should be in root
# This is a placeholder to avoid schema validation errors

name: Placeholder ActionLint Config
on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "This is a placeholder workflow"